### ISSUE TITLE
Add an API endpoint to scan wallet addresses

### ISSUE THREAD

**Issue by iketheadore** [SkycoinProject/skycoin#200]
Add the endpoint `/wallet/scan`, this api would try to find out all the addresses in specific range that has coins. Which is a prerequisite for issue #195 .

Propose of the API:
```
URI: /api/v1/wallet/scan
Method: POST
Args:
    id: wallet id [required]
    num: the number of addresses to scan ahead for balances [optional, must be > 0]
    password: wallet password [optional, must be provided is the wallet is encrypted]
```
